apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.jobName }}"
spec:
  template:
    spec:
      containers:
      - name: "{{ .Values.jobName }}"
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "sleep(50);"]
      restartPolicy: Never
  backoffLimit: 4
